Form
dmitrykorochkin/Loan pull request #6
Opened 2023-01-30 13:12 UTC by dmitrykorochkin

2023-01-30 13:51 UTC, andrey-kudinov requested changes

2023-01-30 13:51 UTC, andrey-kudinov commented on src/modules/form.ts
> +    const setCursorPosition = (pos: any, elem: any) => {
number
HTMLInputElement

2023-01-30 13:51 UTC, andrey-kudinov commented on src/modules/form.ts
> +      } else if (elem.createTextRange) {
Здесь скорее всего не получится типизировать
Можно тут в порядке исключения `any` добавить
(element as any).createTextRange

2023-01-30 13:51 UTC, andrey-kudinov commented on src/modules/form.ts
> +        const formData: any = new FormData(form);
`FormData`

2023-02-01 10:40 UTC, dmitrykorochkin commented on src/modules/form.ts
> +        const formData: any = new FormData(form);
здесь вопрос у меня)

2023-02-01 10:53 UTC, andrey-kudinov requested changes

2023-02-01 10:53 UTC, andrey-kudinov commented on src/modules/form.ts
> +  async postData(url: string, data: string) {
Я так думаю, что ты здесь ожидаешь что твои данные это строка
А на самом деле это FormData

2023-02-01 11:24 UTC, merged